spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apitest?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

jwt:
  secret: mySecretKey123!

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: testbucket975
    stack:
      auto: false
    credentials:
      access-key:
      secret-key:

logging:
  level:
    root: INFO
    com.example.apitest: INFO
